name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch: {}   # allows manual run from Actions tab
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=orange,red,pink,purple,blue&color_dots=#f8f8f8,#ffee55,#ffbb33,#ff8855,#ff5566
            dist/github-contribution-grid-snake-dark.svg?color_snake=orange,red,pink,purple,blue&color_dots=#161b22,#ffee55,#ffbb33,#ff8855,#ff5566

      - name: Push output to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
